### ISSUE TITLE
error: "You must install ECMWF bufrdc library"

### ISSUE THREAD

**Issue by dhwx** [gbvalor/bufr2synop#1]
HI I am having issues installing bufr2synop.

I have installed the ECMWF burfdc library to /usr/lib, and can see a libbufr.a file there...
However I still get the following error message when trying to sudo ./configure:

checking for bufrread in -lbufr... no 
configure: error: "You must install ECMWF bufrdc library"                                                                                                 

the bufrdc version I installed was the latest available..bufrdc_000405.tar.gz

Thanks for any help you can give

**Comment by gbvalor** [comment]
Hello dvwx, sorry by the delay in reply.

I've just installed also bufrdc 000405 . I installed it using gfortran and 32 bits real options. The target directory was '/usr/local/lib'

Then I cloned bufr2synop an configured it without problem. It detected bufr library.

Have you done  'sudo ldconfig' after installed bufrdc ?.  May be libbufr cannot be detected because of this.  I had many problems in the past  after installing new packages ala 'configure make and make install'  because I forgot to run ldconfig.

Tell me if you can finally work with bufr2synop.

**Comment by dhwx** [comment]
Thanks for the reply Guillermo.I have since moved on to trying to work directly with the bufr output, but will let you know if I do try again and how it goes.Dan

**Comment by deksss** [comment]
Hi, I have the same problem and 'sudo ldconfig' dosent help me.
System: Ubuntu 14.04x64

**Comment by TomasZamecnik** [comment]
Same problem, answered in this issue:
[bufrdc lib from ECMWF intstalled and works, but configure won't run](https://github.com/gbvalor/bufr2synop/issues/2)

**Comment by gbvalor** [comment]
The use of ECMWF bufrdc library is deprecated
